global:
  redis:
    address: localhost:6379

release:
  enabled: true
  databaseDriver: postgres
  databaseUrl: "postgresql://postgres:postgres@localhost:5432/release?sslmode=disable"


deploy:
  enabled: true