// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type BcTag struct {
	ID             int64         `json:"id"`
	BoundedContext sql.NullInt64 `json:"bounded_context"`
	Tag            sql.NullInt64 `json:"tag"`
}

type BoundedContext struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Manager   string    `json:"manager"`
	CreatedAt time.Time `json:"created_at"`
}

type Tag struct {
	ID        int64     `json:"id"`
	Tag       string    `json:"tag"`
	CreatedAt time.Time `json:"created_at"`
}
