// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	Createbounded_contexts(ctx context.Context, arg Createbounded_contextsParams) (BoundedContext, error)
	Deletebounded_contexts(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (BoundedContext, error)
	Listbounded_contexts(ctx context.Context, arg Listbounded_contextsParams) ([]BoundedContext, error)
	Listtags(ctx context.Context, arg ListtagsParams) ([]Tag, error)
}

var _ Querier = (*Queries)(nil)
